<?php

namespace AppBundle\Repository;

use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;
use Doctrine\ORM\ORMException;

/**
 * BroadcastEmailListLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BroadcastEmailListLinkRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBroadcastEmailListLinkIDByBroadcast($broadcast)
    {
        try {
            $linkID = $this->createQueryBuilder('link')
                ->setMaxResults(1)
                ->select('link.id')
                ->where('link.broadcast = :broadcast')
                ->andWhere('link.archived = 0')
                ->setParameter('broadcast', $broadcast)
                ->getQuery()
                ->getSingleScalarResult();
            if (!$linkID)
                return false;

            return $this->_em->getReference('AppBundle:BroadcastEmailListLink', $linkID);
        } catch (NoResultException $e) {
            return false;
        } catch (NonUniqueResultException $e) {
            return false;
        } catch (ORMException $e) {
            return false;
        }
    }
}
