<?php

namespace AppBundle\Repository;

/**
 * CapturedHookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CapturedHookRepository extends \Doctrine\ORM\EntityRepository
{
}
