<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * EmailTemplateUserLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailTemplateUserLinkRepository extends \Doctrine\ORM\EntityRepository
{

    public function getTemplatesForUser(User $user) {
        $query = $this->createQueryBuilder('template')
            ->where('template.user = :user')
            ->andWhere('template.archived = 0')
            ->setParameter('user', $user)
            ->orderBy('template.dateCreated', 'DESC')
            ->getQuery();

        return $query->getResult();

    }



}
