<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;
use AppBundle\Entity\EmailListUserLink;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;
use Doctrine\ORM\ORMException;

/**
 * EmailListUserLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailListUserLinkRepository extends \Doctrine\ORM\EntityRepository
{

    public function getEmailListsForUser(User $user) {
        $query = $this->createQueryBuilder('emailLists')
            ->where('emailLists.user = :user')
            ->andWhere('emailLists.archived = 0')
            ->setParameter('user', $user)
            ->orderBy('emailLists.dateCreated', 'DESC')
            ->getQuery();

        return $query->getResult();

    }

    public function getEmailListUserLinkByEmailList($emailList) {
            try {
                $linkID = $this->createQueryBuilder('link')
                    ->setMaxResults(1)
                    ->select('link.id')
                    ->where('link.emailList = :emailList')
                    ->andWhere('link.archived = 0')
                    ->setParameter('emailList', $emailList)
                    ->getQuery()
                    ->getSingleScalarResult();

                if(!$linkID)
                    return false;

                return $this->_em->getReference('AppBundle:EmailListUserLink', $linkID);
            } catch (NoResultException $e) {
                return false;
            } catch (NonUniqueResultException $e) {
                return false;
            } catch (ORMException $e) {
                return false;
            }
    }
}
