<?php

namespace AppBundle\Repository;

/**
 * FunnelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FunnelRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFunnelByUserAndTriggerType(User $user, $triggerType) {

    }
}
