<?php

namespace AppBundle\Repository;

/**
 * funnelEmailListLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class funnelEmailListLinkRepository extends \Doctrine\ORM\EntityRepository
{
}
