<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Funnel;

/**
 * NodeFunnelLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeFunnelLinkRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNodeFunnelLinksByFunnel(Funnel $funnel) {
            $query = $this->createQueryBuilder('link')
                ->where('link.funnel = :funnel')
                ->andWhere('link.archived = 0')
                ->setParameter('funnel', $funnel)
                ->getQuery();
            return $query->getResult();
        }

}
