<?php

namespace AppBundle\Repository;

/**
 * NodeEmailTemplateLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeEmailTemplateLinkRepository extends \Doctrine\ORM\EntityRepository
{
}
