<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Funnel;
use AppBundle\Entity\NodeConnector;

/**
 * NodeConnectorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeConnectorRepository extends \Doctrine\ORM\EntityRepository
{
    public function findStartConnector(Funnel $funnel)
    {
        return $this->findOneBy(array(
            'funnel' => $funnel,
            'isStartNode' => NodeConnector::$START_NODE
        ));
    }
}
