<?php

namespace AppBundle\Repository;

/**
 * ShopifyIntegrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopifyIntegrationRepository extends \Doctrine\ORM\EntityRepository
{
}
