<?php

namespace AppBundle\Repository;

/**
 * SubscriberEmailListLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriberEmailListLinkRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSubscriberEmailListLinksByEmailList($emailList)
    {
        $query = $this->createQueryBuilder('list')
            ->where('list.emailList = :emailList')
            ->andWhere('list.archived = 0')
            ->setParameter('emailList', $emailList)
            ->orderBy('list.dateCreated', 'DESC')
            ->getQuery();
        return $query->getResult();
    }
}
