<?php

namespace AppBundle\Repository;

use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;
use Doctrine\ORM\ORMException;

/**
 * SubscriberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriberRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $email
     * @return bool|mixed
     *
     */
    public function findSubscriberByEmail($email)
    {
        try {
            $currentID = $this->createQueryBuilder('subscriber')
                ->select('subscriber.id')
                ->where("LOWER(subscriber.email) LIKE ? LOWER(:email)")
                ->setParameter('email', $email)
                ->getQuery()
                ->getSingleScalarResult();


            if (!$currentID)
                return false;

            return $this->_em->getReference('AppBundle\Entity\Subscriber', $currentID);
        } catch (NoResultException $e) {
            return false;
        } catch (NonUniqueResultException $e) {
            return false;
        } catch (ORMException $e) {
            return false;
        }
    }
}
