<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;

/**
 * UserIntegrationLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserIntegrationLinkRepository extends \Doctrine\ORM\EntityRepository
{

    public function getIntegrationsForUser(User $user) {
        $query = $this->createQueryBuilder('integration')
            ->where("integration.user = :user")
            ->setParameter('user', $user)
            ->orderBy('integration.dateCreated', 'DESC')
            ->getQuery();

        return $query->getResult();
    }

}
